image: archlinux
packages:
  - nodejs
  - npm
environment:
  build_env: production
  project: skillnews
sources:
  - https://github.com/theskillwithin/skillnews
tasks:
  - prepare: |
      cd ${project}
      npm ci
  - build: |
      cd ${project}
      npm run build
  - lint: |
      cd ${project}
      npm run lint
